# Generated by Django 4.1.5 on 2024-08-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='material',
        ),
    ]
