# Generated by Django 4.1.5 on 2024-08-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_record_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='mobile',
        ),
    ]
