# Generated by Django 4.1.5 on 2024-09-18 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_address_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='remark',
            new_name='dr',
        ),
        migrations.AddField(
            model_name='record',
            name='test_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.test_type'),
            preserve_default=False,
        ),
    ]
