# Generated by Django 4.1.5 on 2024-09-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test_type_rename_remark_record_dr_record_test_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='remark',
            new_name='address',
        ),
    ]
